import React, { useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import '../App.css';
import LogoBot from '../utils/LogoBot.jsx';
import NET from 'vanta/dist/vanta.net.min';
import * as THREE from 'three';
import { useLoading } from '../utils/LoadingContext.jsx';
import { ChartIcon, TargetIcon, BrainIcon, ZapIcon } from './icons';

export default function About() {
  const vantaRef = useRef(null);
  const vantaEffect = useRef(null);
  const navigate = useNavigate();
  const { showPageLoading, hideLoading } = useLoading();

  // Show page loading when component mounts
  useEffect(() => {
    showPageLoading({
      message: "Loading about page...",
      timeout: 800
    });
  }, []);

  // Vanta NET effect
  useEffect(() => {
    if (!vantaEffect.current) {
      vantaEffect.current = NET({
        el: vantaRef.current,
        THREE,
        color: 0x3b82f6,
        backgroundColor: 0x111827,
        highlightColor: 0x1e40af,
        points: 8.0,
        maxDistance: 20.0,
        spacing: 15.0,
        showDots: true,
        mouseControls: true,
        touchControls: true,
        minHeight: 200.00,
        minWidth: 200.00,
      });
    }

    return () => {
      if (vantaEffect.current) {
        vantaEffect.current.destroy();
        vantaEffect.current = null;
      }
    };
  }, []);

  // Hide loading when component is ready
  useEffect(() => {
    const timer = setTimeout(() => {
      hideLoading('page');
    }, 500);
    return () => clearTimeout(timer);
  }, []);

  const handleBackToHome = () => {
    navigate('/');
  };

  return (
    <div className="about-root">
      <div ref={vantaRef} className="about-vanta-bg" />
      <div className="about-container">
        <div className="about-header">
          <div className="about-logo-container">
            <LogoBot className="about-logo" gradientId="about-logo-gradient" size={80} />
          </div>
          <h1 className="about-title">About IntrVu</h1>
          <button className="about-back-btn" onClick={handleBackToHome}>
            ← Back to Home
          </button>
        </div>

        <div className="about-content">
          <div className="about-section">
            <h2 className="about-section-title">What is IntrVu?</h2>
            <p className="about-text">
              IntrVu is an AI-powered platform built to help you excel in machine learning interviews, now with comprehensive coverage of both data and software topics. 
              Whether you're preparing for technical interviews, coding challenges, or system design discussions, 
              our intelligent system delivers personalized practice scenarios and real-time feedback across the full spectrum of data science and software engineering skills.
            </p>
          </div>

          <div className="about-section">
            <h2 className="about-section-title">Key Features</h2>
            <div className="about-features">
              <div className="about-feature-card">
                <div className="about-feature-icon">
                  <BrainIcon size={36} color="#ffffff" />
                </div>
                <h3>AI-Powered Challenges</h3>
                <p>Dynamic interview questions generated by advanced AI models</p>
              </div>
              <div className="about-feature-card">
                <div className="about-feature-icon">
                  <ChartIcon size={36} color="#ffffff" />
                </div>
                <h3>Progress Tracking</h3>
                <p>Monitor your performance with detailed analytics and insights</p>
              </div>
              <div className="about-feature-card">
                <div className="about-feature-icon">
                  <TargetIcon size={36} color="#ffffff" />
                </div>
                <h3>Personalized Learning</h3>
                <p>Adaptive difficulty levels based on your skill progression</p>
              </div>
              <div className="about-feature-card">
                <div className="about-feature-icon">
                  <ZapIcon size={36} color="#ffffff" />
                </div>
                <h3>Real-time Feedback</h3>
                <p>Instant evaluation and suggestions for improvement</p>
              </div>
            </div>
          </div>

          <div className="about-section">
            <h2 className="about-section-title">How It Works</h2>
            <div className="about-steps">
              <div className="about-step">
                <div className="about-step-number">1</div>
                <div className="about-step-content">
                  <h3>Choose Your Challenge</h3>
                  <p>Select from multiple choice questions or scenario-based challenges</p>
                </div>
              </div>
              <div className="about-step">
                <div className="about-step-number">2</div>
                <div className="about-step-content">
                  <h3>Practice & Learn</h3>
                  <p>Work through problems and receive detailed explanations</p>
                </div>
              </div>
              <div className="about-step">
                <div className="about-step-number">3</div>
                <div className="about-step-content">
                  <h3>Track Progress</h3>
                  <p>Monitor your performance and identify areas for improvement</p>
                </div>
              </div>
            </div>
          </div>

          <div className="about-footer">
            <p>Ready to ace your next ML interview?</p>
            <div className="about-footer-tech">
              Powered by OpenAI GPT-4 • Built with React & Python
            </div>
          </div>
        </div>
      </div>
    </div>
  );
} 